### ISSUE TITLE
Doesn't update cache file if CtrlP is installed

### ISSUE THREAD

**Issue by eater** [pbogut/fzf-mru.vim#1]
I've been using this plugin for a while. Then yesterday I (re)installed ctrlp.vim to check something, and I noticed that fzf-mru.vim stopped adding new files to its cache. When I removed ctrlp.vim, it started updating again. Not sure where the conflict is.

**Comment by pbogut** [comment]
Thank you for reporting. I've pushed the fix to the master. `autogroup` still had CtrlP name hence the conflict.
Can you, please confirm if it is working for you now? Thanks.

**Comment by eater** [comment]
Fixed! Thanks.
