### ISSUE TITLE
Documentation is lacking

### ISSUE THREAD

**Issue by lervag** [pbogut/fzf-mru.vim#10]
There is not proper documentation. Optimal solution is to add a `doc/fzf-mru.txt` file in Vim help format, but I would propose a minimal solution is to update the README to document everyhing.

An example of something that is missing: the `g:fzf_mru_exclude` option.

**Comment by pbogut** [comment]
Feel free to create PR.

**Comment by NightMachinery** [comment]
@pbogut Is the MRU thing limited to sorting the initial input to fzf? If not, how exactly does it integrate with fzf's sorting algorithm?

**Comment by lervag** [comment]
> Feel free to create PR.

I've not had the time to do that, but considered to look into it now. Then I noticed you have a PR from March last year that you did not even comment. I don't want to spend time on a PR if I'm not sure it will be properly considered.

**Comment by pbogut** [comment]
@lervag Have a nice day.

**Comment by lervag** [comment]
Thanks; you too :)

**Comment by pbogut** [comment]
@NightMachinary It only sorts initial input. I don't think there is a way to change `fzf` sorting after you start typing in `fzf` window. You can disable sort in `fzf` but then results are far from perfect in my opinion, you can try it with `FZFMru --no-sort`.
