### ISSUE TITLE
Make FZFMru command accept parameters similar to other FZF commands

### ISSUE THREAD

**Issue by spamwax** [pbogut/fzf-mru.vim#12]
I am trying to pass some setting/window size options to FZFMru, following the convention I have found on main [fzf page](https://github.com/junegunn/fzf/blob/master/README-VIM.md)

However I can't seem to make it work and looking at the source code of this plugin, it seems it's not possible to modify `FZFMru` command to accept additional arguments.

For example, I have something like this in my `init.vim`:

```vim
command! -bang -nargs=? Files call fzf#vim#files(<q-args>,
    \  {'window': {'width': 0.9, 'height': 0.6},
    \  'options': ['--reverse']}, <bang>0)
```

Is it possible to change the behavior of `FZFMru` to accept arguments like that?

**Comment by pbogut** [comment]
Hi, you can do `let g:fzf_layout = { 'window': {'width': 0.9, 'height': 0.6} }` in your `init.vim` to set window size.

**Comment by spamwax** [comment]
correct, but that would apply to all zfz related commands.
At the moment I am openning some of fzf commands at the bottom and some as a pop-up overflow.

**Comment by pbogut** [comment]
fair enough, I will think about it. Do you have any suggestions how it should work from user perspective? (I guess second argument would work, as in your first example)

**Comment by spamwax** [comment]
I think `FZFMru` command should be overridable in `init.vim` (at least I couldn't get it work)
Then if user wants to pass only `fzf` options in `command` mode (like `:FZFMRu --reverss`), the plugin should add those (through `<q-args>`) to `{'options': [...]}` dictionary before calling `FZFMru`

On top of that if user wants to totally override the `FZFMru` (like my example above), then `FZFMru` accepts a dictionary type in second argument. 

In case user does both, then `command` mode argument are added to the `options` list of the overridden command's dictionary in `init.vim`.

Ex: user has overridden the `FZFMru` in `init.vim` like this:

```vim
command! -bang -nargs=? FZFMru call fzf_mru#mru(<q-args>,
    \  {'window': {'width': 0.9, 'height': 0.6}, 'options': ['--reverse']}, <bang>0)
```

And then calls `FZFMru` in `command` mode like so:

`:FZFMru --extra-option`

then the final call becomes:

```vim
command! -bang -nargs=? FZFMru call fzf_mru#mru(<q-args>,
    \  {'window': {'width': 0.9, 'height': 0.6},
    \  'options': ['--reverse', '--extra-option']}, <bang>0)
```

hope this makes sense to you.

But if the merging of `options` from `command` mode with override settings is not feasible, then the `init.vim` override always takes over and `command` mode arguments are ignored?

**Comment by pbogut** [comment]
This should work now:

```vim
command! -bang -nargs=? FZFMru call fzf_mru#actions#mru(<q-args>,
    \  {'window': {'width': 0.9, 'height': 0.6},
    \  'options': ['--reverse']})
```

**Comment by spamwax** [comment]
Thanks for addressing this.
Running above directly in `command` mode works. However when I put it in my `init.vim` script it doesn't take effect!.

I have similar `command!` definitions in `init.vim` that are working (for example for `fzf#vim#grep`)!

When enter `:command FZFMru`, I get: 

```vim
:command FZFMru 
    Name              Args Address Complete   Definition                                                                                                                                                                                                                                                                                                      
    FZFMru            *                       call fzf_mru#actions#mru(<q-args>)
```

I'll investigate more to see if it's my setup.

**Comment by spamwax** [comment]
Seems it's not my `nvim` setup.
Running with [this minimal start-up script](https://gist.github.com/spamwax/b541c04b9029491c1c9d5f094656d2ff) has the same effect, i.e., the command override doesn't work.

**Comment by pbogut** [comment]
Well, plugin `command!` was overriding your `command!`. You could use different name, but I guess its better solution to check if command is not defined by user, so I did that.

Your minimal script should work now as expected.

**Comment by spamwax** [comment]
It's working now! Thanks a lot for attending the issue 🙏
