### ISSUE TITLE
Add an MRU option to support selecting multiple files

### ISSUE THREAD

**Issue by anirudhsundar** [pbogut/fzf-mru.vim#19]
Hi,

I was wondering if it would be okay to add a global variable like `g:fzf_mru_multi` or something similar to allow selection of multiple files. I don't want rely on adding `--multi` option to the global FZF options, since that breaks some of the other commands like Ctrl-r recent commands history.

I would be ready to create a PR to add this support if you think this is a valid request.

Thanks,
Anirudh

**Comment by pbogut** [comment]
Hi Anirudh,

I don't use multi select with FZF, but I think you can add `--multi` to MRU call only, did you try that? 
It would be `:FZFMru --multi`, worked when I tried it. 

If you still want to add it as a `g:fzf_mru_multi` option I'm happy to merge it. `fzf_mru#actions#options()` should be the right place to add it.

**Comment by anirudhsundar** [comment]
Ah okay, sorry about that, my mistake. Somehow missed the first point in the Readme Basic Usage that also mentions the fzf-options. I think that should be good enough for now.

Thanks for the reply
