### ISSUE TITLE
Have a way to only list files inside current project

### ISSUE THREAD

**Issue by dlee** [pbogut/fzf-mru.vim#2]
Is there a way to make the MRU only list files from the current project?
I'm working on multiple projects right now, and the MRU is showing files across projects, whereas I would prefer to have each vim session only show the files of that project.

**Comment by pbogut** [comment]
Not exactly. You can use `let g:fzf_mru_relative = 1` to show only files relative to the current root (aka project, I guess). Will that work for you?

**Comment by dlee** [comment]
I don't see a `g:fzf_mru_relative` currently in the repo. Are you saying that you're going to add a configuration variable called `g:fzf_mru_relative`? That would be great.

**Comment by pbogut** [comment]
No, I mean it is there and you can use it now.

`autoload/fzf_mru/mrufiles.vim` line `17`

**Comment by dlee** [comment]
That works perfectly. Thank you!
