### ISSUE TITLE
MRU List is not being refreshed unless Neovim is closed

### ISSUE THREAD

**Issue by ranelpadon** [pbogut/fzf-mru.vim#21]
Similar to https://github.com/pbogut/fzf-mru.vim/issues/6.

I opened/edited the `apps/backoffice/generic/views/event.py` file, but when I run `:FZFMru` it's not included in the list:
<img width="178" alt="Screen Shot 2021-11-13 at 6 07 39 AM" src="https://user-images.githubusercontent.com/4292088/141540530-8296a7f7-3493-4612-86fb-2beecee3239f.png">

But, it's already in the `.cache/fzf_mru/cache.txt` entries:
<img width="579" alt="Screen Shot 2021-11-13 at 6 10 41 AM" src="https://user-images.githubusercontent.com/4292088/141540646-4e76fecc-7338-49ee-998e-f73ee8f40abe.png">

and the `fzf.vim`'s `:History` detected it as well:
<img width="301" alt="Screen Shot 2021-11-13 at 6 07 53 AM" src="https://user-images.githubusercontent.com/4292088/141540852-8224ba8c-5cc3-4547-a5e9-193420efe1f9.png">

It will only be detected when I exit Neovim and open Neovim again. When is the MRU List being updated? Why it's working in `fzf.vim` but not in this plugin? Maybe need to double-check/compare the mechanisms?

Setup:
- Mac OS - Mojave
- Neovim 0.6

BTW, thanks for this plugin. It really has some convenient options. Although this issue is kinda big deal to me since the user would want to query also the recently closed file without exiting Neovim. :)

**Comment by ranelpadon** [comment]
Ok,  I found the reason why it's behaving that way. The current buffer is auto-excluded in the MRU results:
```vim
function! fzf_mru#mrufiles#source()
  " remove current file from the list
  return filter(copy(fzf_mru#mrufiles#list()), 'v:val != expand("%")')
endfunction
```

which is unexpected since a new user of this plugin will have a quick test by opening a single buffer at first, which will update the MRU cache, but will not be displayed since it's the current file, and the only file open. This explains why closing Vim works since when you open Vim again, there's no selected file. Hence, the MRU list is displayed completely as expected. Likewise, closing the buffer without exiting Vim will have the same result.

I think this should be **emphasized in the docs** to minimize surprises? In `fzf.vim`, as we could see in the screenshot above, the current buffer is still included in the MRU list, although it's not clickable. At least, it's explicit in this way.

**Comment by pbogut** [comment]
Well, that's how it was in `CtrlP` when I took this code, and that's how I like it. I don't need to see current file, I know where I am.

We don't have docs for the plugin, but if you want to add that information somewhere in readme feel free to create PR.

If you fancy adding option that will add non-clickable entry to `fzf` list it's still fine by me, as long as it wont change default behaviour.

**Comment by ranelpadon** [comment]
@pbogut Good point about this:
>  I don't need to see current file, I know where I am.

But this might not be intuitive in the very first run (with an empty MRU cache). Also, some MRU plugins (e.g. https://github.com/yegappan/mru) include the current file in the results and you could still select it. `fzf.vim` just added enhancements to make it unclickable. In any case, it's no harm in selecting the current file since it will just go back to that file and sometimes the user might forget where he is. 

Yes, sorry I mean in the `README`:
> We don't have docs for the plugin, but if you want to add that information somewhere in readme feel free to create PR.

Ok, so will create a PR to close this issue:
- add the `fzf_mru_exclude_current_file` option (which excludes the current file by default which is your preference).
- update the README.

Will do it in a bit. Thanks :)
