### ISSUE TITLE
'exclude_current_file' can't be disabled.

### ISSUE THREAD

**Issue by jeroen-dhollander** [pbogut/fzf-mru.vim#25]
According to the documentation `let g:fzf_mru_exclude_current_file = 0` should include the current file, but setting this has no effect.

I managed to fix this by changing

```
  if !empty(s:excur)
```

to
```
    if {s:excur}
```
At [line 157 in mrufiles.vim](https://github.com/pbogut/fzf-mru.vim/blob/master/autoload/fzf_mru/mrufiles.vim#L157)

**Comment by pbogut** [comment]
Thank's, nice catch. Fixed in 5b47c29e66d0546000b2988c4c9dca53f3134f35
