### ISSUE TITLE
Question: how to use g:fzf_mru_store_relative_dirs?

### ISSUE THREAD

**Issue by jeroen-dhollander** [pbogut/fzf-mru.vim#26]
Hey all,

I'm trying to have a shared MRU cache between 3 of my workspaces (all of which are git checkouts of the same repository), which live in the following folders:
   * /path/to/workspace1/src
   * /path/to/workspace2/src
   * /path/to/workspace3/src

Based on the documentation I tried to use `g:fzf_mru_store_relative_dirs` like this:

```
let g:fzf_mru_store_relative_dirs = [ 
      \ '/path/to/workspace1/src',
      \ '/path/to/workspace2/src',
      \ '/path/to/workspace3/src'
      \ ]
```

but that simply seems to break the MRU functionality.

Could anyone here help me understand how to get this to work?

Thanks in advance!

Jeroen

**Comment by pbogut** [comment]
I never used that one, although I switched to worktree flow recently so maybe at some point I will have a closer look at it. For now I like my MRU per tree to be honest.

I've tried it though, and it seams to work with: `g:fzf_mru_relative = 0` if you set this to `1` its busted, I guess that's the case for you?

If you are on linux/mac you can try changing [mrufiles.vim:49](https://github.com/pbogut/fzf-mru.vim/blob/master/autoload/fzf_mru/mrufiles.vim#L49) to `cal filter(a:mrufs, '!stridx(v:val, cwd) || v:val[0] != "/"')`, it should then work with `g:fzf_mru_relative = 1` (assuming, you are not using `Telescope fzf_mru`). I need to think about how to fix properly so it works all right with windows as well.

As to how to use this feature right now I think you can put only parent folder there:
```
let g:fzf_mru_store_relative_dirs = ['/path/to/']
```

The way how it works is if you are in this path it should save files as relative to `cwd`. So you also have to make sure that the `:echo getcwd()` gives you correct folder: `/path/to/workspace1/`, `/path/to/workspace2/`, `/path/to/workspace3/` (or with `/src`, it does no matter but it needs to be consistent).

It modifies only saving of the MRU. So you will not have list of previous recent files before you enabled the option, if that makes sense.

**Comment by jeroen-dhollander** [comment]
Thanks for the response. It does seem to work if I disable `g:fzf_mru_relative`, although the functionality as-is doesn't do what I want it to do (but that's on me I guess ^^).

What it seems to do is store the absolute files, so when I open `~/checkout_1/src/file.h` and then switch to `~/checkout_2` the MRU still suggests ` ~/checkout_1/src/file.h` where I had hoped it would then suggest `~/checkout_2/file.h`.

But I guess that's a different feature than what's currently there, so feel free to ignore this :)

**Comment by pbogut** [comment]
This option should work as you expect it to. The key is that you have to have both:
```
let g:fzf_mru_relative = 0
let g:fzf_mru_store_relative_dirs = ['/path/to/your/workspace/']
```
where your repos are `/path/to/your/workspace/checkout_1` etc.

Edit:
Also, it really should work even with `relative = 1`, it's just broken in that case.
