### ISSUE TITLE
Would be great to exclude files by mask

### ISSUE THREAD

**Issue by 097115** [pbogut/fzf-mru.vim#4]
Me, I use Vim for composing emails with Mutt. And all those temporary files `/private/var/folders/something/something/T/mutt-*` also do appear in the MRU listing :)

**Comment by pbogut** [comment]
Try adding this to your vimrc
`let g:fzf_mru_exclude = ".*/T/mutt-.*"`

**Comment by 097115** [comment]
It seems it works, thanks!

Is it possible to add several masks like this?

**Comment by pbogut** [comment]
Should be.
You may try something like this `"\\(.*/T/mutt-.*\\)\\|\\(your/second/pattern\\)"`.
I think you should use double slashes to escape slash within string, so whenever you would use one slash in regex pattern like this `\(` you should use two like this `\\(`.

**Comment by 097115** [comment]
No, unfortunately that doesn't seem to work... Tried with single slashes, double slashes or even with `\v` or `\\v` instead of slashes: it simply ignores both patterns and does add these files to the list.

Which is strange, since your suggestion indeed appears very logical.

**Comment by 097115** [comment]
Nevermind, it was just me stupid :). Everything works as it should be, thanks for your support.

**Comment by ptzz** [comment]
A few backslashes and parentheses can be shaved off with `'\v.*/T/mutt-.*|your/second/pattern'`.

**Comment by gerases** [comment]
@pbogut  Has that option been removed? I'm not seeing it referenced anywhere in the code.

**Comment by pbogut** [comment]
,@gerases nah, it's there


https://github.com/pbogut/fzf-mru.vim/blob/5b47c29e66d0546000b2988c4c9dca53f3134f35/autoload/fzf_mru/mrufiles.vim#L15

**Comment by gerases** [comment]
Oh, but the option you mentioned is `fzf_mru_exclude`, how does 's:ex' map to that?

**Comment by gerases** [comment]
I have a file in the cache having `abc` in the basename. Should this work:

```
:let g:fzf_mru_exclude = ".*abc.*"
```

for some reason i'm still seeing it.

**Comment by pbogut** [comment]
@gerases It should work. It filters when adding to MRU, if it was added before you changed that option it will still show up. You can call `:call fzf_mru#mrufiles#refresh()` to refresh the list and apply filter on existing items.

**Comment by gerases** [comment]
Yep, it works! Thank you so much! Love the plugin.
