### ISSUE TITLE
File names doesn't stay sorted by recency as user starts typing.

### ISSUE THREAD

**Issue by sampajano** [pbogut/fzf-mru.vim#7]
The MRU files are originally sorted by recency, which is great. But as I start typing, the file list no longer stay sorted by recency, but is seemingly randomly sorted (probably by some FZF algorithm). This isn't very helpful because i'd still like the files i most recently opened to show up top on the MRU list if they are a match.

I think this can be easily fixed by adding a "--no-sort" param here:
https://github.com/pbogut/fzf-mru.vim/blob/master/plugin/fzf_mru.vim#L32

I'm happy to send a PR if we agree this is a better user experience. :)

**Comment by pbogut** [comment]
It makes sense, but since no one  else complained and I kind a like it current way, I don't want to change that behaviour for everyone. I've updated the code so no you can use `let g:fzf_mru_no_sort = 1` configuration to disable sorting while typing. Hope that works for you.
