### ISSUE TITLE
Remove duplicates from MRU list?

### ISSUE THREAD

**Issue by Praful** [pbogut/fzf-mru.vim#8]
I've noticed that there are duplicates in the file list displayed when there is a case difference. In my case it could just be the drive letter (C: vs c:) on Windows. 

Obviously, some OSs have case-sensitive file names but even those it would be unusual to differentiate two files just by case!

However, to cater for both groups, please could you add (if it's not already there!), a variable to allow or disallow duplicates.

**Comment by pbogut** [comment]
You can try `let g:fzf_mru_case_sensitive = 0`, should do the job.

**Comment by Praful** [comment]
Thanks. I may be doing something wrong but it didn't work. 

Does this affect existing MRU file lists? Or will it stop duplicates being put in the list in the future?

I've tried setting the variable before and after the vim-plug line for FZF-MRU.

**Comment by pbogut** [comment]
After checking It looks like it will stop duplicates from being added.
If you don't have too many duplicates you can manually remove them from list file `:exec('e '. fzf_mru#mrufiles#cachefile())`. 

I will keep it open as I think there should be an option to filter list so it works after duplicates were added, but can't commit to any ETA.

**Comment by Praful** [comment]
Thanks for replying. 

In case others find it useful, I used the following command from [StackOverflow](https://stackoverflow.com/questions/14076852/ignore-case-when-removing-duplicates-using-awk)
```
awk -F"," '!x[toupper($1)]++' cache.txt newcache.txt
```
to remove duplicates from the `cache.txt` file. Obviously, you'll have to rename the files for the change to be seen in Vim.

From what you've said, this is a one-time operation since I've now set `g:fzf_mru_case_sensitive = 0`.

Thanks for providing the MRU plugin.

**Comment by Praful** [comment]
After removing the duplicates, they have started reappearing despite including `let g:fzf_mru_case_sensitive = 0`.

I opened a file `C:\...` and `c:\...`, that is, just changing the case of the driver letter. Both entries are in cache.txt.

**Comment by pbogut** [comment]
Are you sure that's the only difference? No double slash or something like that? Have no Windows to check, but can't reproduce it on linux. If I open `File.txt`, `file.txt` and `filE.txt` only one stays in mru list.

**Comment by Praful** [comment]
Yes - I've triple checked!


Here are some repeat entries in `cache.txt`:
```
C:\data\Scripts\Backup-to-wd-4tb.ps1
C:\data\Scripts\backup-to-wd-4tb.ps1
c:\data\Scripts\backup-to-wd-4tb.ps1
```
I deleted the entries for the above in `cache.txt` first.

Typing `:let`, I can see `fzf_mru_case_sensitive #0`

If you can point me to the script that does the comparing, I can do some debugging.

**Comment by pbogut** [comment]
Sure, when you set `g:fzf_mru_case_sensitive` (you set it with `g:`, right?) it is setting script variable `s:cseno` [here](https://github.com/pbogut/fzf-mru.vim/blob/master/autoload/fzf_mru/mrufiles.vim#L16).

[Here](https://github.com/pbogut/fzf-mru.vim/blob/master/autoload/fzf_mru/mrufiles.vim#L69) is [s:addtomrufs](https://github.com/pbogut/fzf-mru.vim/blob/master/autoload/fzf_mru/mrufiles.vim#L69) function. It is checking if [file is already most recent one](https://github.com/pbogut/fzf-mru.vim/blob/master/autoload/fzf_mru/mrufiles.vim#L75) and if not it will [remove it from the list](https://github.com/pbogut/fzf-mru.vim/blob/master/autoload/fzf_mru/mrufiles.vim#L77) and [add as most recent one](https://github.com/pbogut/fzf-mru.vim/blob/master/autoload/fzf_mru/mrufiles.vim#L78).

Unless `!=?` and `!=#` is working different on windows it should work.

**Comment by Praful** [comment]
I put some `echom` in the code but I'm struggling to understand the logic, especially because I've not used vimscript before (but many other languages). This line in particular is opaque to me:

```
  if ( !empty({s:in}) && fn !~# {s:in} ) || ( !empty({s:ex}) && fn =~# {s:ex} )
        \ || !empty(getbufvar('^'.fn.'$', '&bt')) || !filereadable(fn) | retu

```
This is where I scattered some `echom` print statements:

```
fu! s:addtomrufs(fname)
  echom "addtomrufs =================="
  echom "case_sensitive = " . g:fzf_mru_case_sensitive 
  echom "fname = " . a:fname
  let fn = fnamemodify(a:fname, ':p')
  let fn = exists('+ssl') ? tr(fn, '/', '\') : fn
  echom "s:in = " . s:in
  echom "s:ex = " . s:ex
  echom "fn = " . fn
  if ( !empty({s:in}) && fn !~# {s:in} ) || ( !empty({s:ex}) && fn =~# {s:ex} )
        \ || !empty(getbufvar('^'.fn.'$', '&bt')) || !filereadable(fn) | retu
  en
  echom "s:cseno = " . s:cseno
  let idx = index(s:mrufs, fn, 0, !{s:cseno})
  echom "idx = " . idx
  if idx
    cal filter(s:mrufs, 'v:val !='.( {s:cseno} ? '#' : '?' ).' fn')
    cal insert(s:mrufs, fn)
    if {s:soup} && idx < 0
      cal s:savetofile(s:mergelists())
    en
  en
endf
```

Here is some output:

```
addtomrufs ==================
case_sensitive = 0
fname = LinuxHome\vimfiles\vimplug\fzf-mru.vim\autoload\fzf_mru\mrufiles.vim
s:in = g:fzf_mru_include
s:ex = g:fzf_mru_exclude
fn = c:\data\LinuxHome\vimfiles\vimplug\fzf-mru.vim\autoload\fzf_mru\mrufiles.vim
s:cseno = g:fzf_mru_case_sensitive
idx = -1
savetofile ==================
"LinuxHome\vimfiles\vimplug\fzf-mru.vim\autoload\fzf_mru\mrufiles.vim" [unix] 164L, 4590C
addtomrufs ==================
case_sensitive = 0
fname = mrufiles.vim
s:in = g:fzf_mru_include
s:ex = g:fzf_mru_exclude
fn = c:\data\LinuxHome\vimfiles\vimplug\fzf-mru.vim\autoload\fzf_mru\mrufiles.vim
s:cseno = g:fzf_mru_case_sensitive
idx = 0
addtomrufs ==================
case_sensitive = 0
fname = mrufiles.vim
s:in = g:fzf_mru_include
s:ex = g:fzf_mru_exclude
fn = c:\data\LinuxHome\vimfiles\vimplug\fzf-mru.vim\autoload\fzf_mru\mrufiles.vim
s:cseno = g:fzf_mru_case_sensitive
idx = 0
"[No Name]" --No lines in buffer--
addtomrufs ==================
case_sensitive = 0
fname = mrufiles.vim
s:in = g:fzf_mru_include
s:ex = g:fzf_mru_exclude
fn = c:\data\LinuxHome\vimfiles\vimplug\fzf-mru.vim\autoload\fzf_mru\mrufiles.vim
s:cseno = g:fzf_mru_case_sensitive
idx = 0
"mrufiles.vim" 164 lines --50%--
"mrufiles.vim" [unix] 164L, 4590C written
addtomrufs ==================
case_sensitive = 0
fname = mrufiles.vim
s:in = g:fzf_mru_include
s:ex = g:fzf_mru_exclude
fn = c:\data\LinuxHome\vimfiles\vimplug\fzf-mru.vim\autoload\fzf_mru\mrufiles.vim
s:cseno = g:fzf_mru_case_sensitive
idx = 0
addtomrufs ==================
case_sensitive = 0
fname = mrufiles.vim
s:in = g:fzf_mru_include
s:ex = g:fzf_mru_exclude
fn = c:\data\LinuxHome\vimfiles\vimplug\fzf-mru.vim\autoload\fzf_mru\mrufiles.vim
s:cseno = g:fzf_mru_case_sensitive
idx = 0
addtomrufs ==================
case_sensitive = 0
fname = !cmd.exe
s:in = g:fzf_mru_include
s:ex = g:fzf_mru_exclude
fn = c:\data\LinuxHome\vimfiles\vimplug\fzf-mru.vim\autoload\fzf_mru\!cmd.exe
addtomrufs ==================
case_sensitive = 0
fname = mrufiles.vim
s:in = g:fzf_mru_include
s:ex = g:fzf_mru_exclude
fn = c:\data\LinuxHome\vimfiles\vimplug\fzf-mru.vim\autoload\fzf_mru\mrufiles.vim
s:cseno = g:fzf_mru_case_sensitive
idx = 0
```

The above somewhere resuled in 
```
C:\data\LinuxHome\vimfiles\vimplug\fzf-mru.vim\autoload\fzf_mru\mrufiles.vim
```
being added to the list (capital C).

Is it possible that at some point the script is comparing `mrufiles.vim` with the full path `c:\data\LinuxHome\vimfiles\vimplug\fzf-mru.vim\autoload\fzf_mru\mrufiles.vim` ?

Happy to try any suggestions/code.

**Comment by pbogut** [comment]
Closing coz its old and inactive. If its still an issue let me know.
