### ISSUE TITLE
Blend MRU with FZF results

### ISSUE THREAD

**Issue by harryjubb** [pbogut/fzf-mru.vim#9]
Apologies if this is possible already and I've missed it in the documentation.

What I would like is to have all of the current directory FZF results available, but sorted by recency first, then FZF sort order afterwards; so that I can find any file in my project that I'm looking for, but have the most recent available first.

Is this possible?

**Comment by pbogut** [comment]
It's not supported now and I'm not even sure if it's possible. 

You would have to feed `fzf` with sorted file list, but then it would sort it again when you start type. You can use `--no-sort` option but then results wont be good.

 If you on linux and using `rg` you can try:
`(cat ~/.cache/fzf_mru/cache.txt; rg -l '' $(pwd)) | fzf`
and
`(cat ~/.cache/fzf_mru/cache.txt; rg -l '' $(pwd)) | fzf --no-sort`

First only works until you start typing, results for second are poor.

My take on it is it's not possible with `fzf`, you would have to be able to add some sort of weight to recent files to `fzf` sorting algorithm.
